apiVersion: v1
kind: Secret
metadata:
  name: secret 
  namespace: chatapp
type: Opaque
data:
  JWT_SECRET: ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKU2IyeGxJam9pUVdSdGFXNGlMQ0pKYzNOMVpYSWlPaUpKYzNOMVpYSWlMQ0pWYzJWeWJtRnRaU0k2SWtwaGRtRkpibFZ6WlNJc0ltVjRjQ0k2TVRjMU1UWXlNekl3TUN3aWFXRjBJam94TnpVeE5qSXpNakF3ZlEuUm5DWEVtMUFTclF4Qmp3bk5pZ2J4TDA0SnlmeXZQUmVwcTlQTWIwMXpvOA== #eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTc1MTYyMzIwMCwiaWF0IjoxNzUxNjIzMjAwfQ.RnCXEm1ASrQxBjwnNigbxL04JyfyvPRepq9PMb01zo8


